### PR TITLE
Update with drush

### PR DESCRIPTION
**Pull request by DigitLib**
like as in master README.md

**JIRA Ticket**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

A brief description of what the intended result of the PR will be and/or what problem it solves.

# What's new?
A in-depth description of the changes made by this PR. Technical details and possible side effects.

Example:
* Changes x feature to such that y
* Added x
* Removed y

# How should this be tested?

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by bondjimbond** [comment]
@DigitLib Did you cut a second branch for this? (I see patch-1 pulled against 7.x, and patch-2 against 7.x-1.12)... It's best to use the same branch (patch-1) to make a PR against both 7.x and 7.x-1.12, so that there's no difference between them. (e.g. if you have to make a change, don't need to make it twice.)

**Comment by DigitLib** [comment]
@bondjimbond I don't know how to do this so I did it like this.
How can I connect same patch?

**Comment by DiegoPino** [comment]
@bondjimbond sometimes using the same branch to pull against release and 7.x is complicated and can bring other unexpected changes, what is most important here (since 7.x-1.12 will never be developed on after release) is that the number of lines changed and the files match (for those files that need to be equal, excludes, of course, .info files). In this case, this one has fewer lines than the 7.x patch-1 branch.

One option @DigitLib is to simply create a new local branch in your fork based on 7.x-1.12 and on that one apply the diff of the previous one, which you can see here  https://patch-diff.githubusercontent.com/raw/Islandora/islandora_xacml_editor/pull/142.diff
then make this pull again using that new branch (patch-3?)

**Comment by bondjimbond** [comment]
@DiegoPino Yep, seeing the different number of lines is what spawned my comment. Whatever approach you take, must make sure it's the same as the other. 👍

**Comment by DiegoPino** [comment]
@DigitLib also, instead of the diff, simply copy and paste the full content of the other README into that new branch's README and commit using the same message as before. Many paths to the same results

**Comment by DigitLib** [comment]
@DiegoPino TNX! What I did is a copy of new added lines to new patch on a same place. @bondjimbond now I look at line numbers it the same 38-55 for add in both and a last line is 85.

**Comment by DigitLib** [comment]
@DiegoPino Copy a whole README.md is also good idea should I do that?

**Comment by DiegoPino** [comment]
@DigitLib patch-2 is +18 lines and -0
Previous one is +19 -1

"Copy a whole README.md is also good idea should I do that", yes!, seems to be the simples approach.

**Comment by DigitLib** [comment]
Clipboard ready and....

**Comment by bondjimbond** [comment]
@DigitLib the difference is line 81: https://github.com/Islandora/islandora_xacml_editor/pull/142/files#diff-04c6e90faac2675aa89e2176d2eec7d8R81

In patch-1 you edited the links at line 81 to be https. In patch-2 they're still http.

**Comment by DigitLib** [comment]
@bondjimbond Sorry I sow it... Added new PR copied from patch-1 to 7.12...
Sorry for mess :(

**Comment by bondjimbond** [comment]
Thanks for the new pull. I'll close this one.

**Pull request closed without merging**
